#!/bin/bash
#repositório pessoal
case $1 in
-lista) echo "ø" | curl -s https://github.com/hulaneoTi/scriptsBash | grep -o '/main/.*"' | sed -e 's/\/main\///g; s/"//g; /reposit/d' ;;
reposit) echo "Impossível chamar o reposit" ;;
*) source <(curl -s https://raw.githubusercontent.com/hulaneoTi/scriptsBash/main/$1) ;;
esac
