#!/bin/bash
echo '
[ -z "$TMUX"  ] && { tmux attach || exec tmux new-session && exit;}
read -p "informe a senha do usuario: " -s senha
caminho=`wslpath "$(cmd.exe /C "echo|set /p="%USERPROFILE%"")"`
alias update="echo $senha | sudo -S apt update && apt upgrade -y"
alias desktop="cd $caminho\/OneDrive\ -\ TI\ Safe/Área\ de\ Trabalho/"
unset caminho
unset senha
export PATH=$PATH:./
clear
alias repo="source <(curl -s https://raw.githubusercontent.com/hulaneoTi/scriptsBash/main/reposit)"
alias bombapatch="programas=(tmux htop neofetch hollywood ranger);for i in ${programas[@]}; do which $i &>- || sudo apt install $i; done; unset programas"
' >> ~/.bash_profile
