#!/bin/bash
echo "#!/bin/bash
{

URL_PING='www.google.com' #Ideally, change this to your routers IP address
ADAPTER='wlan0'
TICKRATE=20

while true
do

	/DietPi/dietpi/func/dietpi-notify 2 "Checking connnection for: $ADAPTER"
		ping -I $ADAPTER -c 1 $URL_PING
		if (( $? != 0 )); then

			/DietPi/dietpi/func/dietpi-notify 2 "Detected connection loss: $ADAPTER. Reconnecting"
			ifdown "$ADAPTER"
			sleep 1
			ifup "$ADAPTER"
			/DietPi/dietpi/func/dietpi-notify 0 'Completed'

		else

			/DietPi/dietpi/func/dietpi-notify 0 "Connection $ADAPTER"

		fi

		sleep $TICKRATE

	done

	exit 0

}" > /etc/dietpi/dietpi-wifi-monitor.sh

chmod +x  /etc/dietpi/dietpi-wifi-monitor.sh

cat << _EOF_ > /etc/systemd/system/dietpi-wifi-monitor.service
[Unit]
Description=Monitors loss of WiFi connection and automatically reconnects
After=network.target network-online.target

[Service]
Type=simple

ExecStart=/bin/bash -c /etc/dietpi/dietpi-wifi-monitor.sh

[Install]
WantedBy=multi-user.target
_EOF_
systemctl daemon-reload
systemctl enable dietpi-wifi-monitor.service
systemctl start dietpi-wifi-monitor.service

echo 'alias wifimonitor="systemctl status dietpi-wifi-monitor.service -l"' > ~/.bash_profile